language: ruby

rvm:
  - 3.1.2
  - 3.2.0

cache:
  directories:
  - $HOME/nats-server

before_install:
  - bash ./scripts/install_nats.sh

before_script:
  - export PATH=$HOME/nats-server:$PATH

sudo: required
dist: jammy

addons:
  hosts:
    - server-A.clients.nats-service.localhost
    - server-A.clients.fake-nats-service.localhost
    - server-A.routes.nats-service.localhost
    - server-A.routes.fake-nats-service.localhost

jobs:
  include:
  - name: "Ruby: 3.3.0"
    rvm: "3.3.0-preview1"
  - name: "Ruby: 3.2.0 (nats-server@v2.9)"
    rvm: "3.2.0"
    env:
    - NATS_SERVER_VERSION=v2.9.24
  - name: "Ruby: 3.2.0 (nats-server@main)"
    rvm: "3.2.0"
    env:
    - NATS_SERVER_VERSION=main
  allow_failures:
    - name: "Ruby: 3.3.0"
    - name: "Ruby: 3.2.0 (nats-server@main)"
